apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
  labels:
    app.kubernetes.io/name: hello-api
    app.kubernetes.io/instance: ic2-hello-api
    project: ic2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-api
    spec:
      # imagePullSecrets: # 如果是公开镜像不需要这个，保留结构供参考
      #   - name: registry-secret
      containers:
        - name: hello-api-container
          # ！！！ 关键：这是占位符，不是实际地址
          image: ic2-hello-api-image
          ports:
            - containerPort: 8080
              name: http-hello-api
          resources:
            # 适配 1G 内存节点的 Base 配置
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "20m"