# apps/backend/hello-api/base/hello-api-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-api-ingress
  labels:
    app.kubernetes.io/name: hello-api
    project: ic2
  annotations:
    # 确保 Traefik 识别
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: dev.hello.test.com
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: hello-api
                port:
                  number: 80