apiVersion: v1
kind: Service
metadata:
  name: web-em
  labels:
    app.kubernetes.io/name: web-em
    project: ic2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-web
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: web-em