apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik  # 关键：必须和你 Ingress 里的 ingressClassName 一致
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true" # 设为默认，防止漏网之鱼
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  controller: traefik.io/ingress-controller