# apps/backend/admin-api/base/admin-api-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-api-ingress
  labels:
    app.kubernetes.io/name: admin-api
    project: ic2
spec:
  ingressClassName: traefik
  rules:
    - host: dev.admin.test.com
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin-api
                port:
                  number: 80