apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: hello-api
  - path: ingress-traefik-patch.yaml
    target:
      kind: Ingress
      name: hello-api-ingress

# ！！！ 核心调整：镜像替换策略
images:
  - name: ic2-hello-api-image # 对应 Base 中的占位符
    newName: iceymoss/go-hello    # 替换为真实的轻量级镜像
    newTag: "1.0"            # 替换 Tag
