apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Automatically add the ic2-backend namespace to all resources
namespace: backend

resources:
  - backend-ingress.yaml # Shared Backend API Ingress configure

