# apps/backend/admin-api/overlays/development/ingress-traefik-patch.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-api-ingress
  namespace: backend
  # annotations:  <-- 如果只剩这一行也没关系，或者整个删掉
spec:
  # ingressClassName: traefik  <-- 这一行一定要删掉！
  rules:
    - host: dev.api.test.com
      http:
        paths:
          - path: /admin/
            pathType: Prefix
            backend:
              service:
                name: admin-api
                port:
                  number: 80