# apps/backend/admin-api/overlays/development/ingress-traefik-patch.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-api-ingress
  # 这里不要写 annotations: null，直接删掉这一块
spec:
  rules:
    - host: dev.admin.test.com
      http:
        paths:
          # 只修改路径为根路径 /
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-api
                port:
                  number: 80